INFRA := $(shell git root)/infra

include ${INFRA}/oct-hd.mk

GENPDFS := 010-Apx.pdf

HARDPDFS := \
	110-19-01-22-DD-FROM-AVRO-TO-OCT-BERAN-1ST-INTERACTION.pdf \
	120-20-01-22-DD-FAIL-BAL-143.pdf  \
	130-09-05-22_2.5K-DEBT.pdf

include ${INFRA}/oct.mk