INFRA := $(shell git root)/infra
include ${INFRA}/oct-hd.mk

GENPDFS := 010-Apx.pdf

HARDPDFS := \
	020-GmailCoverErrorsAvroBill.pdf \
	030-DetailsErrorsAvroBill.pdf

ALLPDFS :=${GENPDFS} ${HARDPDFS}

include ${INFRA}/oct.mk